// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC52-B0J2BqEaO-mbJMcvxJvcqKHOII7N0',
    appId: '1:742312457368:web:3243dd1de4d2b3aedf0ced',
    messagingSenderId: '742312457368',
    projectId: 'airsense-v1',
    authDomain: 'airsense-v1.firebaseapp.com',
    databaseURL: 'https://airsense-v1-default-rtdb.firebaseio.com',
    storageBucket: 'airsense-v1.firebasestorage.app',
    measurementId: 'G-0V9FS8JWB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF3Pkd1klGo5LrGj9pSZL_CSYr2wXRK-I',
    appId: '1:742312457368:android:ec2dbe7f3d2b7514df0ced',
    messagingSenderId: '742312457368',
    projectId: 'airsense-v1',
    databaseURL: 'https://airsense-v1-default-rtdb.firebaseio.com',
    storageBucket: 'airsense-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2MC_NMEPhwfmLCEKl8vJMf1qjHxaIElE',
    appId: '1:742312457368:ios:71e844aabb312195df0ced',
    messagingSenderId: '742312457368',
    projectId: 'airsense-v1',
    databaseURL: 'https://airsense-v1-default-rtdb.firebaseio.com',
    storageBucket: 'airsense-v1.firebasestorage.app',
    iosBundleId: 'com.example.ecosensetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2MC_NMEPhwfmLCEKl8vJMf1qjHxaIElE',
    appId: '1:742312457368:ios:71e844aabb312195df0ced',
    messagingSenderId: '742312457368',
    projectId: 'airsense-v1',
    databaseURL: 'https://airsense-v1-default-rtdb.firebaseio.com',
    storageBucket: 'airsense-v1.firebasestorage.app',
    iosBundleId: 'com.example.ecosensetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC52-B0J2BqEaO-mbJMcvxJvcqKHOII7N0',
    appId: '1:742312457368:web:19c7b267ee973124df0ced',
    messagingSenderId: '742312457368',
    projectId: 'airsense-v1',
    authDomain: 'airsense-v1.firebaseapp.com',
    databaseURL: 'https://airsense-v1-default-rtdb.firebaseio.com',
    storageBucket: 'airsense-v1.firebasestorage.app',
    measurementId: 'G-H9CJE70EM9',
  );
}
