final List<String> allTips = [
  "Use non-toxic cleaning products.",
  "During storms, avoid unnecessary travel.",
  "To improve air quality, keep your HVAC system well-maintained.",
  "Use electric or hand-powered tools instead of gas-powered ones.",
  "Check the air quality index before outdoor activities.",
  "Avoid idling your vehicle engine.",
  "Avoid metal objects during lightning.",
  "Use an air purifier indoors to reduce pollutants.",
  "In hot weather, monitor news and weather updates.",
  "Check weather forecasts daily.",
  "Keep emergency kits ready during extreme weather.",
  "To reduce pollution, avoid using your car when possible.",
  "Avoid outdoor activities during thunderstorms.",
  "When it's cold, monitor news and weather updates.",
  "Reduce energy use at home to lower industrial pollution.",
  "Avoid smoking indoors to maintain air freshness.",
  "Support clean energy solutions in your community.",
  "Keep your windows closed on high pollution days.",
  "Compost organic waste instead of burning it.",
  "Learn first aid for weather-related health issues.",
  "When it's cold, keep your phone charged for alerts.",
  "To reduce pollution, use eco-friendly cleaning products.",
  "To reduce pollution, switch to renewable energy sources.",
  "During storms, stay indoors if possible.",
  "Service your car regularly to reduce emissions.",
  "Keep warm clothes accessible in winter.",
  "Protect pets during harsh weather.",
  "Stock up on essentials before a weather emergency.",
  "Cover windows during hurricanes or strong winds.",
  "During storms, monitor news and weather updates.",
  "For better air, keep your HVAC system well-maintained.",
  "Avoid using elevators during lightning storms.",
  "When it's cold, avoid unnecessary travel.",
  "For better air, use eco-friendly cleaning products.",
  "When it's cold, wear appropriate clothing.",
  "Limit car use and opt for public transport or cycling.",
  "Wear sunscreen on sunny days.",
  "For better air, plant more trees and greenery.",
  "To reduce pollution, plant more trees and greenery.",
  "When it's cold, stay indoors if possible.",
  "Plant indoor plants to naturally clean the air.",
  "Use fans instead of air conditioners when possible.",
  "To improve air quality, avoid using your car when possible.",
  "To improve air quality, plant more trees and greenery.",
  "To improve air quality, switch to renewable energy sources.",
  "Avoid using aerosol sprays and choose eco-friendly options.",
  "Keep your home well-ventilated when air quality allows.",
  "Walk or bike short distances instead of driving.",
  "During storms, keep your phone charged for alerts.",
  "Avoid burning wood or trash outdoors.",
  "Stay hydrated during hot weather.",
  "Avoid flooded roads during heavy rain.",
  "During storms, wear appropriate clothing.",
  "For better air, switch to renewable energy sources.",
  "For better air, avoid using your car when possible.",
  "In hot weather, avoid unnecessary travel.",
  "Dress in layers during cold weather.",
  "To improve air quality, use eco-friendly cleaning products.",
  "Carry an umbrella during rainy seasons.",
  "Secure outdoor items before storms.",
  "In hot weather, wear appropriate clothing.",
  "Upgrade to energy-efficient appliances.",
  "To reduce pollution, keep your HVAC system well-maintained.",
  "In hot weather, stay indoors if possible.",
  "Stay indoors during heatwaves.",
  "Drive slowly during fog or heavy rain.",
  "In hot weather, keep your phone charged for alerts.",
  "Advocate for greener policies in your local area.",
  "Use weather apps to stay updated.",
];
